### ISSUE TITLE
What are the features?

### ISSUE THREAD

**Issue by Kaned1as** [velikodniy/cmr-fuse#11]
Hi, what are this project differencies with this one?

https://gitlab.com/Kanedias/MARC-FS

**Comment by g0ddest** [comment]
MARC-FS was created in Oct 16, this project in Aug 16.

After a brief view I can say that in MARC-FS files are read fully into memory before reading so cmr-fuse spilt it into little parts. Uploading (not implemented yet) I think will be split too. cmr-fuse also support mulithreading. Also we plan to add in cmr-fuse a stream encryption.  Also as a feature cmr-fuse is written on pure C while MARC-FS is written on C++.
I think @velikodniy can add to the above.

**Comment by g0ddest** [comment]
Also cmr-fuse tested in MacOS (osxfuse) and in Linux. MARC-FS working only in Linux.

**Comment by Kaned1as** [comment]
Thanks, sounds reasonable
